=== kokizzu/anime-offline-database/schemas/dead-entries.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/manami-project/anime-offline-database/raw/master/schemas/dead-entries.schema.json",
    "title": "List of dead entries for anime-offline-database",
    "description": "A list of anime IDs resulting in a 'not found' error or which would lead to adult content which is not publicly available. Basically anime IDs which don't require any further download attempt.",
    "type": "object",
    "required": [
        "license",
        "repository",
        "lastUpdate",
        "deadEntries"
    ],
    "properties": {
        "license": {
            "description": "Information about the license of the dataset.",
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "name": {
                    "description": "Name of the license.",
                    "const": "Open Data Commons Open Database License (ODbL) v1.0 + Database Contents License (DbCL) v1.0"
                },
                "url": {
                    "description": "URL to the whole license file.",
                    "type": "string",
                    "format": "uri"
                }
            }
        },
        "repository": {
            "description": "URL of this github repository which is the source of the dataset.",
            "type": "string",
            "const": "https://github.com/manami-project/anime-offline-database"
        },
        "lastUpdate": {
            "description": "The date on which the file was updated in the format: YYYY-MM-DD.",
            "type": "string",
            "format": "date"
        },
        "deadEntries": {
            "description": "IDs of anime which have been removed from the respective meta data provider.",
            "type": "array",
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        }
    }
}

=== kokizzu/anime-offline-database/dead-entries/animenewsnetwork.json
{
  "$schema": "https://raw.githubusercontent.com/manami-project/anime-offline-database/refs/tags/2025-24/dead-entries/dead-entries.schema.json",
  "license": {
    "name": "Open Data Commons Open Database License (ODbL) v1.0 + Database Contents License (DbCL) v1.0",
    "url": "https://github.com/manami-project/anime-offline-database/blob/2025-24/LICENSE"
  },
  "repository": "https://github.com/manami-project/anime-offline-database",
  "lastUpdate": "2025-06-11",
  "deadEntries": [
    "2588"
  ]
}
